# -*- mode: ruby -*-
# vi: set ft=ruby :

nodes = {
    'web'           => [1, 10],
    'redis'         => [1, 20],
    'rabbitmq'      => [1, 30],
}

Vagrant::Config.run do |config|
    config.vm.box = "precise32"
    config.vm.box_url = "D:\\Somkiat\\training\\geeky\\vagrant+puppet\\precise32.box"

    nodes.each do |prefix, (count, ip_start)|
        count.times do |i|
            hostname = "%s-%02d" % [prefix, (i+1)]

            config.vm.define "#{hostname}" do |box|
                box.vm.host_name = "#{hostname}.vagrant.internal"
                box.vm.network :hostonly, "33.33.33.#{ip_start+i}"
                box.vm.provision :puppet do |puppet|
                    puppet.manifests_path = "puppet/manifests"
                    puppet.manifest_file = "#{prefix}.pp"
                    puppet.module_path = "puppet/modules"
                end
                box.vm.customize [
                    "modifyvm", :id,
                    "--name", hostname,
                    "--memory", "512",
                ]
            end
        end
    end
end