# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|
  
	config.vm.box = "geeky-academy"
	config.vm.box_url = "D:\\Somkiat\\training\\geeky\\vagrant+puppet\\precise32.box"

	config.vm.network :hostonly, "33.33.33.10"
	config.vm.share_folder "foo", "/var/www", "./webapp"

	config.vm.customize [
		"modifyvm", :id,
		"--name", "geeky-academy-01",
		"--memory", "512",
	]

end
